name: Daily Updates

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
          commit_filename: devcard.png
          commit_message: "chore: update ${filename}"
        
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: SVG Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nickmoline
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          config_output: svg
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_pagespeed: no
          plugin_pagespeed_url: https://www.nickmoline.com
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.nickmoline.com/feed.xml
          plugin_tweets: no
          plugin_tweets_token: ${{ secrets.TWITTER_SECRET }}
          plugin_tweets_limit: 2
          plugin_tweets_user: NickMoline
      - name: PNG Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nickmoline
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          config_output: png
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_pagespeed: no
          plugin_pagespeed_url: https://www.nickmoline.com
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.nickmoline.com/feed.xml
          plugin_tweets: no
          plugin_tweets_token: ${{ secrets.TWITTER_SECRET }}
          plugin_tweets_limit: 2
          plugin_tweets_user: NickMoline
      - name: Markdown Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nickmoline
          template: markdown
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.md
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_pagespeed: no
          plugin_pagespeed_url: https://www.nickmoline.com
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.nickmoline.com/feed.xml
          plugin_tweets: no
          plugin_tweets_token: ${{ secrets.TWITTER_SECRET }}
          plugin_tweets_limit: 2
          plugin_tweets_user: NickMoline
